//> using publish.organization "io.github.alexarchambault.tmp.test"
//> using publish.moduleName "zip-input-stream"
//> using publish.computeVersion "git:tag"
//> using publish.repository "central-s01"
//> using publish.license "GPL-2.0-with-classpath-exception"
